### ISSUE TITLE
Program új locale entryk könnyű létrehozására

### ISSUE THREAD

**Issue by ExAtom** [14A-A-Lyedlik-Devs/Gump#15]
Ez a program bekérné, hogy milyen típusú entryt akarna a felhasználó létrehozni (jelenleg badge vagy ui), majd az új entry azonosítóját, végül pedig egyesével megkérdezi, hogy mi legyen az egyes nyelveken a szöveg. A nyelv listát a locales mappában található json-ök alapján szedi ki. Az entryket ABC rendbe teszi azonosító alapján.

Névnek talán jó, hogy **LocaleCreator**.

Az apps-ba szerintem simán mehet a saját mappájába, még teszteket is kaphat, hogy lássák, profik vagyunk ;)

- [ ] App elkészítése
- [ ] Tesztek elkészítése

**Comment by Rettend** [comment]
ez nem csak egy kis program lesz hanem rendesen bele lesz építve az admin részbe szóval a Locale Backend és Frontend issue-kban fogjuk számontartani
