### ISSUE TITLE
language csak a létező nyelvek listájából lehet valamelyik

### ISSUE THREAD

**Issue by Rettend** [14A-A-Lyedlik-Devs/Gump#64]
```[tasklist]
### Tasks
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/102
```

**Comment by ExAtom** [comment]
Majd ha lesz megoldás githubról kiolvasni, akkor jöhet egy új issue (vagy akár ez újranyitva), hogy legyen itt implementálva, addig is closeolom
